import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
        <head>
        <meta name="color-scheme" content="light" />
        </head>
      <body>
        <nav className="h-[76px] bg-[#fff]">

        </nav>
        {children}
      </body>
    </html>
  );
}
